### PR TITLE
Bump Rails to 5.2.1

### PR DESCRIPTION
**Pull request by greysteil**
Should be totally backwards compatible with 5.2.0. 🎉

### CODE REVIEW

**Comment by vavgustov** [comment]
Thanks for the PR! Seems Semaphore CI failed due to 'flaky' test https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests. I'll check and merge at the end of the week.

**Comment by greysteil** [comment]
@vavgustov - just pushed a commit that should fix the flaxy spec. Capybara won't wait for any async code to finish if you use `not_to have_content`, so instead `to have_no_content` should be used.

If you want to thank me, I would love you to use [Dependabot](https://dependabot.com) on this repo. It's totally free, and I think will save you time and help keep snibox up-to-date, but I also have an ulterior motive: I'm keen to get more open source apps using it so I can use the data on the CI runs for dependency updates to find bugs in new releases and point the maintainers to the failing CI run as a reproduction step.

Having well-tested open-source apps like snibox use it should enable it to do awesome things, like automatically test release candidates of Rails and report back on any breakages, etc.

What do you reckon?

**Comment by vavgustov** [comment]
hi @greysteil,

I know about [Dependabot](https://dependabot.com/). I think some time ago I noticed it from [Octobox](https://github.com/octobox/octobox). However I prefer next strategy about dependencies:
1. Update dependencies after GitHub notifications about security vulnerabilities
2. Update dependencies once per 3-6 months

At this moment these steps have better time balance for me. But I will keep Dependabot in the head.

**Comment by greysteil** [comment]
Oh rad - still puts a smile on my face when folks have heard of it.

That makes sense. If you want to automate the GitHub security vulnerability bit you could add it and set it up to only create security-related PRs (it sources from RubySec as well as GitHub Security Alerts, so a slight improvement) but given that flow it sounds like you don’t need much automation.

Thanks for the response, and for snibox!

**Pull request merged**
